### ISSUE TITLE
Falback strategy

### ISSUE THREAD

**Issue by EmWhyy** [Cari1111/NumberPlateRecognition#32]
Right now we use our model on a cropped image of a car. What should we do if our model did not detect the licence plate correctly.
- run it again on a smaller image, maybe we can cut some parts of the bounding box which we got from the car. The edges are mostly not needed and also is the upper and lower part of the image probably a tier or just the roof of the car.

**Comment by TheDying0fLight** [comment]
I think we should instead try training a better model since a cropped image of the car should be enough to recognize the number plates
